name: CostumeContest
version: '${version}'
main: me.quickscythe.shadowcore.HauntedHavoc
api-version: '1.21'
dependencies:
  server:
    ShadowUtils:
      load: BEFORE
      required: true
      join-classpath: true